# Generated by Django 5.1.1 on 2024-09-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_customuser_managers_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
